name: "B2500 Meter Dev"
version: "1.0.3.1"
slug: b2500_meter
description: >-
  "Replicates a Smart Meter device for a B2500 energy storage system while allowing integration with various smart meters."
arch:
  - amd64
  - aarch64
  - armv7
url: "https://github.com/ebogaard/b2500-meter"
image: "ghcr.io/ebogaard/b2500-meter-addon"
panel_icon: "mdi:meter-electric"
init: false
startup: services
homeassistant_api: true
hassio_api: true
hassio_role: homeassistant
host_network: true
ports:
  12345/tcp: 12345
  12345/udp: 12345
  1010/udp: 1010
  2222/udp: 2222
  2223/udp: 2223
map:
  - type: addon_config
    read_only: false
options:
  power_input_alias: "sensor.current_power_in"
  power_output_alias: ""
  poll_interval: 1
  disable_absolute_values: false
  device_types: "ct001"
schema:
  power_input_alias: str
  power_output_alias: str?
  poll_interval: int(1,)
  disable_absolute_values: bool
  device_types: str
  custom_config: str?
